import pickle,math,sys,os,string,shutil
from re import X
import numpy as np
import pandas as pd

path = os.getcwd()


def main():
    available_deck_positions = [i for i in range(1,10)]
    dispenseParameters = {}
    dispenseParameters['reservoirDeckSlot'] = int(input('In which slot on the Opentrons deck will your reservoir be? '))
    available_deck_positions.remove(dispenseParameters['reservoirDeckSlot'])
    dispenseParameters['reservoirType'] = None
    while dispenseParameters['reservoirType'] not in ['single', 'divided']:
        dispenseParameters['reservoirType'] = input('What type of reservoir will you be using? [single, divided] ')
    dispenseParameters['reservoirLocation'] = 'A1'
    if dispenseParameters['reservoirType'] == 'divided':
        dispenseParameters['reservoirLocation'] = None
        while dispenseParameters['reservoirLocation'] not in ['A'+str(i) for i in range(1,13)]:
            dispenseParameters['reservoirLocation'] = input('Which channel of the divided reservoir would you like to distribute? [A1, A2, ... A12]: ')
    dispenseParameters['plateType'] = []
    dispenseParameters['destinationPlates'] = []
    newPlate = 0
    while newPlate not in available_deck_positions:
        newPlate = int(input('Which slots on the Opentrons deck contain plates to dispense to? Slots {} are currently available: '.format(available_deck_positions)))
    dispenseParameters['destinationPlates'].append(newPlate)
    available_deck_positions.remove(newPlate)
    plateType = ''
    while plateType not in ['96-well', '384-well']:
        plateType = input('Into what types of plates would you like to dispense? [96-well, 384-well]: ')
    dispenseParameters['plateType'].append(plateType)
    anotherPlate = 'y'
    while anotherPlate != 'n' and len(available_deck_positions) != 0:
        anotherPlate = input('Would you like to fill a deck slot with a plate to dispense to? [y,n]: ')
        if anotherPlate == 'y':
            newPlate = 0
            while newPlate not in available_deck_positions:
                newPlate = int(input('Which slot on the Opentrons deck will the plate be in? Slots {} are currently available: '.format(available_deck_positions)))
            dispenseParameters['destinationPlates'].append(newPlate)
            available_deck_positions.remove(newPlate)
            plateType = ''
            while plateType not in ['96-well', '384-well']:
                plateType = input('Into what types of plate would you like to dispense? [96-well, 384-well]: ')
            dispenseParameters['plateType'].append(plateType)
    
    dispenseParameters['volume'] = float(input('What volume would you like to aliquot to each well? (uL): '))
    
    print(dispenseParameters)
    pickle.dump(dispenseParameters, open('{}/BenchItems.pkl'.format(path), 'wb'))
    print('Please use the \"Advanced\" settings on the robot to launch a Jupyter Notebook and upload the BenchItems.pkl generated by this script to the robot.')
    

if __name__== "__main__":
    main()
